// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as item$0 from "../item/models.js";

/**
 * @returns {$CancellablePromise<void>}
 */
export function Clear() {
    return $Call.ByID(3413102416);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function Copy(id) {
    return $Call.ByID(4237301486, id);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function Delete(id) {
    return $Call.ByID(3493858492, id);
}

/**
 * GetImage returns a base64-encoded PNG suitable for embedding in a data URL.
 * @param {string} id
 * @returns {$CancellablePromise<string>}
 */
export function GetImage(id) {
    return $Call.ByID(2597896766, id);
}

/**
 * @param {string} query
 * @returns {$CancellablePromise<item$0.Item[]>}
 */
export function List(query) {
    return $Call.ByID(3815708967, query).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function Pin(id) {
    return $Call.ByID(75301334, id);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function Unpin(id) {
    return $Call.ByID(3494679967, id);
}

// Private type creation functions
const $$createType0 = item$0.Item.createFrom;
const $$createType1 = $Create.Array($$createType0);
